INCLUDE MACROS.TXT

DATA SEGMENT
    ; ADD YOUR DATA HERE!
    PKEY DB "INSERT 4 DECIMAL NUMS AND THEN <ENTER>...$"
    MESSAGE1 DB "GIVE FOUR NUMBERS: $"
    MESSAGE2 DB "HEX = $"
    NEW_LINE DB 0AH, 0DH, '$' ;OI ASCII KWDIKOI GIA ALLAGH GRAMMHS
ENDS

STACK SEGMENT
    DW   128  DUP(?)
ENDS

CODE SEGMENT

MAIN PROC FAR
; SET SEGMENT REGISTERS:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX

START:

    PRINT_STRING MESSAGE1
    CALL DEC_KEYBOARD   ; KATEU8EIAN ME TO READ TA BAZEIS STON BP A8ROIZONTAS
    PRINT_STRING NEW_LINE 
BCK:
    READ
    CMP AL,0DH    ;koita gia enter
    JE CNT
    CMP AL,'Q'
    JE QUIT
    CMP AL,'q'
    JE QUIT
    JMP BCK

CNT:
    PRINT_STRING MESSAGE2
    ;TUPWSE TA HEX TOU 16BITOU BP
    CALL DIGITS_TO_HEXS
    PRINT_STRING NEW_LINE
    JMP START
    
    
QUIT:
	MOV AL,0H
    EXIT
         
MAIN ENDP

         
;==========PROCEDURES=============
DEC_KEYBOARD PROC NEAR
    MOV DX, 0
    MOV CX, 4 ;GIATI 8A DEXTW 4 ARI8MOUS

IGNORE:
    READ
    CMP AL,'Q'
    JE QUIT
    CMP AL,'q'
    JE QUIT
    CMP AL, '0'
    JL IGNORE
    CMP AL, '9'
    JG IGNORE
    SUB AL, 30H 
    MOV BL,AL   ;APO8UKEUSE TO TREXON STON BL
    MOV BH,0
    MOV AX,DX   ; FORTWSE TO PROHGOUMENO A8ROISMA APO DX
    MOV DX,10   ;BALE STO DL 10
    MUL DX      ;AX=AX*10
    ADD AX,BX   ;+BL
    MOV DX,AX   ;KAI BALTO PALI STO DX
    LOOP IGNORE
    MOV BP,DX    
    RET
    
DEC_KEYBOARD ENDP


    
;======MAKE 16 BITS TO HEX=======  

DIGITS_TO_HEXS PROC NEAR
	 ; KSEKINAME APO TA MSB KAI TYPWNOYME HEX ANA 4DES
     MOV BX, BP
     MOV BL, BH ;APOMONWNW TA 4 MSB
     SHR BL, 4  ;OLIS8HSE TA STIS 4 LEAST SIGNIF 8ESEIS
     CALL PRINT_HEX
     MOV BX, BP
     MOV BL,BH
     AND BL, 0FH
     CALL PRINT_HEX
     MOV BX, BP
     AND BL, 0F0H
     SHR BL, 4
     CALL PRINT_HEX
     MOV BX, BP
     AND BL, 0FH
     CALL PRINT_HEX
     
     
     RET    
DIGITS_TO_HEXS ENDP

PRINT_HEX PROC NEAR
    CMP BL,9 ;AN O ARI8MOS EINAI METAKSU 0 K 9 PROS8ETW 30H
    JG ADDR1 
    ADD BL, 30H
    JMP ADDR2

ADDR1:
    ADD BL, 37H ;DIAFORETIKA PROS8ETW 37H ('A' = 41H)
ADDR2:
    PRINT BL
    RET  
    
PRINT_HEX ENDP
;======END OF MAKE 16 BITS TO HEX========
 
    
END MAIN
