INCLUDE MACROS.TXT
;============DATA SEGMENT===============
DATA SEGMENT
    MESSAGE1 DB "GIVE A 10-BINARY NUMBER: $" 
    MESSAGE2 DB "DECIMAL: $"  
    PKEY DB "PRESS ANY KEY TO START OR Q IN ORDER TO EXIT. $" 
    NEW_LINE DB 0AH, 0DH, '$'   ;OI ASCII KWDIKOI GIA ALLAGH GRAMMHS
ENDS
;============STACK SEGMENT==============
STACK SEGMENT
    DW 128 DUP(?)
ENDS

;============CODE SEGMENT===============
CODE SEGMENT 
    ASSUME CS:CODE, SS:STACK, DS:DATA, ES:DATA


MAIN PROC FAR
     
; SET SEGMENT REGISTERS:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX   
    
START:
    PRINT_STRING MESSAGE1       ; PRINT_STRING ME XRHSH TOY MACRO
    CALL BIN_KEYBOARD           ; O XRHSTHS DINEI TON BINARY
    PUSH DX
    PRINT_STRING NEW_LINE       ; ALLAGH GRAMMHS
    PRINT_STRING MESSAGE2
    POP DX
    CALL DEC_CONVERTION         ; TON METATREPW SE DEKADIKO
    PRINT_STRING NEW_LINE       ; ALLAGH GRAMMHS
    PRINT_STRING PKEY           ; ODHGIES PROS TON XRHSTH GIA TO TI NA PATHSEI
    READ                        ; DIABAZEI AUTO POU EDWSE O XRHSTHS
    CMP AL, 'Q'                 ; AN PATH8HKE TO Q
    JE QUIT                     ;  TELOS PROGRAMMATOS 
    CMP AL, 'q'                 ; AN PATH8HKE TO q
    JE QUIT                     ;  TELOS PROGRAMMATOS
    PRINT_STRING NEW_LINE       ; ALLAGH GRAMMHS
    JMP START
QUIT:
    MOV AL,0H 
    EXIT                        ; APO TO MACRO
    

MAIN ENDP
;========DIABASMA TOY BINARY APO TO KEYBOARD============
BIN_KEYBOARD  PROC NEAR 
    MOV DX, 0
    MOV CX, 10  ; O CX EINAI DEFAULT COUNTER GIA LOOPS. 8ELW 10 NOUMERA NA DIABASW 
       
IGNORE:
    READ        ; DIABAZEI XARAKTHRA APO PLHKTROLOGIO XWRIS NA TO TUPWSEI
    CMP AL, 'Q' ; BLEPW AN EINAI Q
    JE QUIT     ; AN EINAI TOTE KANOUME EXIT   
    CMP AL, 'q' ; BLEPW AN EINAI Q
    JE QUIT     ; AN EINAI TOTE KANOUME EXIT   
    SHL DX,1
    CMP AL, '0' ; ALLIWS,BLEPW AN EINAI 0
    JE ZERO     
    CMP AL, '1' ; ALLIWS,BLEPW AN EINAI 1
    JE ONE    
    JMP IGNORE
ONE:            
    INC DX      ; GIA NA DIABASW 10 ARI8MOUS...
ZERO:  
    LOOP IGNORE    
ADDR2:
    RET   
    
BIN_KEYBOARD ENDP

;=========METATROPH K PRINT SE DEKADIKO==================
DEC_CONVERTION PROC NEAR
    MOV AX,DX
    MOV DX,0
    ;O DX::AX EINAI O DEFAULT DIAIRETEOS
    MOV BX, 1000 
    DIV BX          ; DIAIRW ME 1000 
    PRINT_NUM AL    ; TO AL EXEI TO PHLIKO DHLADH THN XILIADA
    MOV AX,DX       ; DIAIRETHS 8A GINEI TO PROHGOUMENO UPOLOIPO
    MOV DX,0
    MOV BX, 100     ; DIAIRW ME 100
    DIV BL
    PRINT_NUM AL    ; TO AL 8A EXEI TO PHLIKO POU 8A NAI OI EKATONTADES
    MOV AL,AH       ; DIAIRETHS 8A GINEI TO PROHGOUMENO UPOLOIPO      
    MOV AH,0
    MOV BX, 10      ; DIAIRW ME 10
    DIV BL 
    PRINT_NUM AL    ; TO PHLIKO EDW EXEI TIS DEKADES
    PRINT_NUM AH    ; TO UPOLOIPO EDW EXEI TIS MONADES
    
    RET
    
DEC_CONVERTION ENDP
;=============================================================
CODE ENDS

END MAIN
