INCLUDE MACROS.TXT
;============DATA SEGMENT===============
DATA SEGMENT
    MESSAGE1 DB "GIVE A 10-BINARY NUMBER: $" ;EDW PREPEI NA MPEI META TO INPUT DE KSERW AKRIBWS PWS
    MESSAGE2 DB "DECIMAL: $"  ; EDW PREPEI NA MPEI TO OUTPUT, OUTE K EDW KSERW PWS AKRIBWS :P
    PKEY DB "PRESS ANY KEY TO START OR Q IN ORDER TO EXIT. $" 
    NEW_LINE DB 0AH, 0DH, '$'   ;OI ASCII KWDIKOI GIA ALLAGH GRAMMHS
ENDS
;============STACK SEGMENT==============
STACK SEGMENT
    DW 128 DUP(?)
ENDS

;============CODE SEGMENT===============
CODE SEGMENT 
    ASSUME CS:CODE, SS:STACK, DS:DATA, ES:DATA


MAIN PROC FAR
     
; SET SEGMENT REGISTERS:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX   
    
START:
    PRINT_STRING MESSAGE1      ;PRINT_STRING APO THN MACRO
    CALL BIN_KEYBOARD          ;O XRHSTHS DINEI TON BINARY
    PUSH DX
    PRINT_STRING NEW_LINE      ;ALLAGH GRAMMHS
    PRINT_STRING MESSAGE2
    POP DX
    CALL DEC_CONVERTION        ;TON METATREPW SE DEKADIKO
    PRINT_STRING NEW_LINE      ;ALLAGH GRAMMHS
    PRINT_STRING PKEY          ;ODHGIES PROS TON XRHSTH GIA TO TI NA PATHSEI
    READ                       ;DIABAZEI AUTO POU EDWSE O XRHSTHS
    CMP AL, 'Q'                ;AN PATH8HKE TO Q
    JE QUIT                    ; TELOS PROGRAMMATOS 
    CMP AL, 'q'                ;AN PATH8HKE TO Q
    JE QUIT                    ; TELOS PROGRAMMATOS
    PRINT_STRING NEW_LINE      ;ALLAGH GRAMMHS
    JMP START
QUIT:
    EXIT                       ;APO THN MACRO
    

MAIN ENDP
;========DIABASMA TOY BINARY APO TO KEAYBOARD============
BIN_KEYBOARD  PROC NEAR 
    ;PUSH  DX ;EPHREAZETAI APO THN MACRO PRINT 
    MOV DX, 0
    MOV CX, 10   ;O CX EINAI DEFAULT COUNTER GIA LOOPS. 8ELW 10 NOUMERA NA DIABASW 
       
IGNORE:
    READ         ;DIABAZEI XARAKTHRA APO PLHKTROLOGIO XWRIS NA TO TUPWSEI
    CMP AL, 'Q'  ;BLEPW AN EINAI Q
    JE QUIT      ;AN EINAI TOTE KANOUME EXIT   ; H' ALLIWS JE ADDR2
    CMP AL, 'q'  ;BLEPW AN EINAI Q
    JE QUIT      ;AN EINAI TOTE KANOUME EXIT   ; H' ALLIWS JE ADDR2
    SHL DX,1
    CMP AL, '0'  ;ALLIWS,BLEPW AN EINAI 0
    JE ZERO    ;JUMP IF LESS APO TO 0 (TOTE TO AGNOOUME)
    CMP AL, '1'  ;ALLIWS,BLEPW AN EINAI 1
    JE ONE    ;JUMP IF GREATER APO TO 1 (TOTE TO AGNOOUME)
    JMP IGNORE
ONE:            
    INC DX   ;GIA NA DIABASW 10 ARI8MOUS...
ZERO:  
    LOOP IGNORE    
ADDR2:
    ;POP DX
    RET   
    
BIN_KEYBOARD ENDP

;=========METATROPH K PRINT SE DEKADIKO==================
DEC_CONVERTION PROC NEAR
    ;STON DX EXW TON BINARY ARI8MO MOU
    MOV AX,DX
    MOV DX,0
    ;BAZW TON DX (BINARY ARI8MO MOU STON AX GIATI O AX EINAI O DEFAULT DIAIRETEOS
    MOV BX, 1000 
    DIV BX       ; DIAIRW ME 1000 
    PRINT_NUM AL ;TO AL EXEI TO PHLIKO DHLADH THN XILIADA
    MOV AX,DX    ; DIAIRETHS 8A GINEI TO PROHGOUMENO UPOLOIPO
    MOV DX,0
    MOV BX, 100  ;DIAIRW ME 100
    DIV BL
    PRINT_NUM AL ;TO AL 8A EXEI TO PHLIKO POU 8A NAI OI EKATONTADES
    MOV AL,AH    ; DIAIRETHS 8A GINEI TO PROHGOUMENO UPOLOIPO      
    MOV AH,0
    MOV BX, 10   ; DIAIRW ME 10
    DIV BL 
    PRINT_NUM AL ; TO PHLIKO EDW EXEI TIS DEKADES
    PRINT_NUM AH ; TO UPOLOIPO EDW EXEI TIS MONADES\
    
    RET
    
DEC_CONVERTION ENDP
;=============================================================
CODE ENDS

END MAIN