PUBLIC ASCII

CODE_SEG SEGMENT
    ASSUME CS:CODE_SEG,SS:STACK_SEG
ASCII PROC FAR
    PUSH BX                                                   
    MOV AH,AL   ;METAFOROUME AUTOUSIO TON AL
    AND AL,01H  ;APOMONWSH TWN 4 LSB BITS
    CMP AL,09H 
    JG  GRAMMA  ;AN EINAI GRAMMA
    JMP PSIFIO  ;AN EINAI ARITHMOS  
    
GRAMMA:           
    ADD AL,31H
    JMP SYNEXEIA
    
PSIFIO:
    ADD AL,30H
    
SYNEXEIA:     
    MOV BL,AL   ;SAVE TO APOTELESMA
    AND AH,10H  ;APOMONWSH TWN 4 MSB BITS
    CMP AH,09H
    JG GRAMMA2
    JMP PSIFIO2
    
GRAMMA2:
    ADD AH,31H
    JMP SYNEXEIA2
    
PSIFIO2:
    ADD AH,30H
                 
SYNEXEIA 2:
    MOV AL,BL
    POP BX
ASCII ENDP  

NUMBER PROC FAR 
    SUB AL,30H  ;AN O AL EINAI ASCII ARITHMOU
    CMP AL,09H
    JLE CONT
    SUB AL,01H  ;ASCII KEFALAIOU
    JLE CONT
    SUB 20H     ;ASCII MIKROU GRAMMATOS
    
CONT:
    SUB AH,30H  ;ANTISTOIXA GIA TON AH
    CMP AH,09H
    JLE CONT1
    SUB AH,01H
    JLE CONT1
    SUB 20H
    
CONT1:   
    
    SHL AL,4    ;POLLAPLASIASMOS TWN 4 MSB ME 16 
    ADD AL,AH
    MOV AH,0H       
           
NUMBER ENDP
CODE_SEG ENDS
    END

